version: "3.9"

services:
  image-service:
    build: ./image-service
    ports:
      - "8001:8000"

  pcd-service:
    build: ./pcd-service
    ports:
      - "8002:8000"

  robot-status-service:
    build: ./robot-status-service
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0

  slam_nav-service:
    build: ./slam_nav-service
    ports:
      - "8004:8000"

  db-service:
    build: ./db-service
    ports:
      - "8005:8000"

  camera-service:
    build: ./camera-service
    devices:
      - /dev/video2:/dev/video2    # FLIR Boson
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4    # RealSense
      - /dev/video5:/dev/video5
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "8007:8000"
    privileged: true

  gateway:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - image-service
      - pcd-service
      - robot-status-service
      - camera-service
