version: "3.9"

services:
  image-service:
    build: ./image-service
    ports:
      - "8001:8000"

  pcd-service:
    build: ./pcd-service
    ports:
      - "8002:8000"

  robot-status-service:
    build: ./robot-status-service
    ports:
      - "8003:8000"

  slam_nav-service:
    build: ./slam_nav-service
    ports:
      - "8004:8000"
  
  db-service:
    build: ./db-service
    ports:
      - "8005:8000"

  gateway:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - image-service
      - pcd-service
      - robot-status-service
  